base: 'https://team-members.ddev.site/'
dependencies:
  - kkroff/tm-site
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    locale: de_DE.UTF-8
    navigationTitle: Deutsch
    flag: de
rootPageId: 1
websiteTitle: Team-Members
